### PR TITLE
add more quick fixes for specific error types

### LINKED ISSUE #687: code action to fix `reportUnusedCallResult`
fixes it by just adding an assignment to `_`

i guess this is redundant if we do both #683 and #198? but we should probably still add it for users who don't like inlay hints

### PR DESCRIPTION
**Pull request by NCBM**
- `reportUnnecessaryCast`: remove unnecessary `cast` call
- `reportUnusedCallResult`: assign to `_`
- `reportSelfClsDefault`: remove default parameter

fixes #687

### CODE REVIEW

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 1]
```diff
@@ -176,6 +176,145 @@ export class CodeActionProvider {
...
+                            const callNode = node;
+                            if (
+                                (callNode.d.leftExpr.nodeType === ParseNodeType.Name &&
+                                    callNode.d.leftExpr.d.value === 'cast') ||
+                                (callNode.d.leftExpr.nodeType === ParseNodeType.MemberAccess &&
+                                    callNode.d.leftExpr.d.leftExpr.nodeType === ParseNodeType.Name &&
+                                    callNode.d.leftExpr.d.leftExpr.d.value === 'typing' &&
+                                    callNode.d.leftExpr.d.member.d.value === 'cast')
+                            ) {
+                                castCallNode = callNode;
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: this is inconsistent with how `reportUnnecessaryCast` detects `cast` calls. this won't work the cast function isn't called `cast`:

```py
from typing import cast

foo = cast

asdf = foo(int, int(1))
```

should probably use `FunctionType.isBuiltIn(functionType, ['typing.cast', 'typing_extensions.cast'])` instead, which is consistent with the logic used when reportting the error

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 2]
```diff
@@ -176,6 +176,145 @@ export class CodeActionProvider {
...
+                    }
+                }
+                if (castCallNode && castCallNode.nodeType === ParseNodeType.Call) {
+                    const valueArg = castCallNode.d.args[1];
+                    const startPos = convertOffsetToPosition(valueArg.start, lines);
+                    const endPos = convertOffsetToPosition(valueArg.start + valueArg.length, lines);
+                    const leftRange = { start: convertOffsetToPosition(castCallNode.start, lines)!, end: startPos };
+                    const rightRange = {
+                        start: endPos,
+                        end: convertOffsetToPosition(castCallNode.start + castCallNode.length, lines)!,
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: `!` isn't needed, `convertOffsetToPosition` always returns a `Position`
```suggestion
                    const leftRange = { start: convertOffsetToPosition(castCallNode.start, lines), end: startPos };
                    const rightRange = {
                        start: endPos,
                        end: convertOffsetToPosition(castCallNode.start + castCallNode.length, lines),
```

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 3]
```diff
@@ -176,6 +176,145 @@ export class CodeActionProvider {
...
+                                break;
+                            }
+                        }
+                        node = node.parent;
+                    }
+                }
+                if (castCallNode && castCallNode.nodeType === ParseNodeType.Call) {
+                    const valueArg = castCallNode.d.args[1];
+                    const startPos = convertOffsetToPosition(valueArg.start, lines);
+                    const endPos = convertOffsetToPosition(valueArg.start + valueArg.length, lines);
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: maybe a more descriptive name for these variables could be `valueStartPosition` and `valueEndPosition`

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 4]
```diff
@@ -176,6 +176,145 @@ export class CodeActionProvider {
...
+                    }
+                }
+            }
+
+            // ==== CA for reportUnusedCallResult ====
+            if (rule === DiagnosticRule.reportUnusedCallResult) {
+                // Suggestion to assign the result to `_`
+                // Insert an edit at the start of the diagnostic range
+                const position = diagnostic.range.start;
+                const insertText = `_ = `;
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: nit: backticks are only really used when doing string interpolation (the javascript equivalent of an f-string) or multiline strings.
```suggestion
                const insertText = '_ = ';
```

File: packages/pyright-internal/src/tests/fourslash/removeSelfClsDefault.invokeCodeAction.fourslash.ts [hunk 5]
```diff
@@ -0,0 +1,36 @@
+/// <reference path="typings/fourslash.d.ts" />
+
+// @filename: pyrightconfig.json
+//// {
+////   "typeCheckingMode": "recommended"
+//// }
+
+// @filename: test.py
+//// class Foo:
+////     def bar(self[|/*default*/ = None|]):
```
Comment (DetachHead) [inline packages/pyright-internal/src/tests/fourslash/removeSelfClsDefault.invokeCodeAction.fourslash.ts]: can we also have a test for when there's a type annotation

**Review by DetachHead — COMMENTED** [review]
thanks!

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 6]
```diff
@@ -176,6 +177,148 @@ export class CodeActionProvider {
...
+                const lineText = lines.getItemAt(diagnostic.range.start.line);
+                let node = findNodeByOffset(
+                    parseResults.parserOutput.parseTree,
+                    diagnostic.range.start.character + lineText.start
+                );
+                if (node) {
+                    while (node) {
+                        if (node.nodeType === ParseNodeType.Call) {
+                            const completer = this._createCompleter(workspace, fileUri, token, node, lines);
+                            const type = completer.evaluator.getTypeOfExpression(node.d.leftExpr).type;
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: no need to create a completer here since you're only using the `evaluator`
```suggestion
                            const evaluator = workspace.service.backgroundAnalysisProgram.program.evaluator!;
                            const type = evaluator.getTypeOfExpression(node.d.leftExpr).type;
```
