### PR TITLE
fix: don't comment out return types in stub generation

### LINKED ISSUE #1694: don't comment out return types when generating stubs
### Description

https://github.com/DetachHead/basedpyright/blob/c7f2768d1c86b201fd53618fcf09a0b26cca798f/packages/pyright-internal/src/analyzer/typeStubWriter.ts#L293-L304

no idea what the point of commenting it is. deliberately creating a less complete stub for no reason?

### PR DESCRIPTION
**Pull request by veeceey**
## Summary

Removes the logic that was adding inferred return types as comments when generating type stubs. This was unnecessarily creating less complete stubs by commenting out potentially useful type information.

## Changes

- Removed the code block in `typeStubWriter.ts` (lines 293-304) that would:
  1. Check if a function has no return type annotation
  2. Infer the return type
  3. Add it as a comment like `# -> int:`

This logic was deliberately creating incomplete stubs for no clear reason.

## Related Issues

Fixes #1694

## Test Plan

- TypeScript compilation passes without errors
- No existing tests were found for the stub writer functionality
- Manual verification would require:
  1. Running stub generation on code with unannotated functions
  2. Verifying the generated stubs no longer have commented return types

### CODE REVIEW

File: packages/pyright-internal/src/analyzer/typeStubWriter.ts [hunk 1]
```diff
@@ -290,19 +290,6 @@ export class TypeStubWriter extends ParseTreeWalker {
...
-            if (!returnAnnotation) {
-                const functionType = this._evaluator.getTypeOfFunction(node);
-                if (functionType && isFunction(functionType.functionType)) {
-                    let returnType = this._evaluator.getInferredReturnType(functionType.functionType);
-                    returnType = removeUnknownFromUnion(returnType);
-                    if (!isNever(returnType) && !isUnknown(returnType)) {
-                        line += ` # -> ${this._evaluator.printType(returnType, { enforcePythonSyntax: true })}:`;
-                    }
-                }
-            }
```
Comment (DetachHead) [inline packages/pyright-internal/src/analyzer/typeStubWriter.ts:304]: we should keep this, just remove the part that makes it a comment

Comment (veeceey) [reply packages/pyright-internal/src/analyzer/typeStubWriter.ts:304]: Done\! I've restored the inferred return type logic but changed it to set `returnAnnotation` instead of appending a comment. Now when there's no explicit return type annotation, the inferred type gets emitted as a proper `-> type` annotation in the stub rather than as a `# -> type:` comment.
