### PR TITLE
fix normal variables incorrectly getting a `TypeAlias` inlay hint if their type came from a type alias

### LINKED ISSUE #183: values incorrectly have the `TypeAlias` inlay hint if their type comes from a type alias
```py
Foo = int

def asdfasdf(bar: Foo):
    baz = bar
```
image

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #183

### CODE REVIEW

File: packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts [hunk 1]
```diff
@@ -113,7 +122,11 @@ export class TypeInlayHintsWalker extends ParseTreeWalker {
                 this.featureItems.push({
                     inlayHintType: 'variable',
                     position: node.start + node.length,
-                    value: `: ${getTypeAliasInfo(type) ? 'TypeAlias' : this._printType(type)}`,
+                    value: `: ${
+                        getTypeAliasInfo(type) && type.flags & TypeFlags.Instantiable
```
Comment (KotlinIsland) [inline packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts:126]: there are many types that are not instantiable
