### PR TITLE
add code action quick-fix to add `@override`

### LINKED ISSUE #1627: `reportImplicitOverride` should offer a quick-fix to add `@override`
### Description

Consider [this playground](https://basedpyright.com/?typeCheckingMode=all&code=MYGwhgzhAEBiD28BcBYAUNT0AmBTAZtAEZgBOAFBLiPgDTQAeS0AlgHYAuAlKhlvwAdS7DuQZd0ktKEgwAQmABe5BPB7p%2BeQiQpUa9Jq07q%2B-TEJFiJp6EA) example.
It would be nice if basedpyright added a quickfix for adding `@override` to a method, if the current Python version and `basedpyright.analysis.useTypingExtensions` allow it.

### PR DESCRIPTION
**Pull request by NCBM**
fixes #1627

### CODE REVIEW

**Comment by DetachHead** [comment]
to get auto imports working, you can probably use the same method i used for completions

https://github.com/DetachHead/basedpyright/blob/0b0e72765593409f5d04e7175849cbb9835d1e49/packages/pyright-internal/src/languageService/completionProvider.ts#L559-L575

**Comment by NCBM** [comment]
> to get auto imports working, you can probably use the same method i used for completions

The AutoImporter does import, however I firstly tried and found that it still does import even when the symbol is already imported - this causes duplicate imports.

Using CompletionProvider is also currently not possible - it can only process the symbol already been in the document.

I'm not sure either duplicate import or letting users do double-fix would be better, or there are better solutions?

**Comment by DetachHead** [comment]
i was able to get it working. i just pushed my changes. needs to be cleaned up a bit though (mainly the duplicated code)

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 1]
```diff
@@ -64,117 +73,169 @@ export class CodeActionProvider {
...
         const lines = parseResults.tokenizerOutput.lines;
 
-        if (diags.find((d) => d.getActions()?.some((action) => action.action === Commands.import))) {
-            const offset = convertPositionToOffset(range.start, lines);
-            if (offset === undefined) {
-                return [];
-            }
+        if (!workspace.rootUri) {
+            return codeActions;
+        }
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: this check can't go before the import suggestions. see #824

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 2]
```diff
@@ -64,117 +73,169 @@ export class CodeActionProvider {
...
+                    return [];
+                }
+
+                const decoratorTextEdit: TextEdit = {
+                    range: {
+                        start: { line: decoratorLine.line, character: indent.length },
+                        end: { line: decoratorLine.line, character: indent.length },
+                    },
+                    newText: `\n${indent}@override`,
+                };
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]:
```py
class Foo:
    def foo(self):...

class Bar(Foo):
    def foo(self):
        ...
```

applying the code action in this example seems to be boken:

```py
from typing import override


class Foo:
    def foo(self):...

clas
    @overrides Bar(Foo):
    def foo(self):
        ...
```
(tested in vscode)

the version in `completionProvider.ts` doesn't have this issue (and it also accounts for other scenarios such as other decorators being present). i recommend extracting that logic into a function or something that can be used in both the completion provider and the code action provider

**Review by DetachHead — COMMENTED** [review]
thanks for the contribution

File: packages/pyright-internal/src/languageService/codeActionProvider.ts [hunk 3]
```diff
@@ -64,117 +66,141 @@ export class CodeActionProvider {
...
+                    node as FunctionNode,
+                    offset,
+                    undefined,
+                    methodLineContent,
+                    completionMap
+                );
+
+                if (overrideEdits.length === 0) {
                     continue;
                 }
```
Comment (DetachHead) [inline packages/pyright-internal/src/languageService/codeActionProvider.ts]: this prevents the "add `# pyright: ignore`" code action from being created if this condition is `true` (which can happen when targeting python <3.12 and `basedpyright.analysis.useTypingExtensions` is disabled)

[more info](https://docs.basedpyright.com/latest/benefits-over-pyright/language-server-improvements/#automatically-inserting-the-override-decorator)

**Comment by NCBM** [comment]
looks like some execution order randomly incorrect (check before parse) on this macos test. maybe related to a new issue or some hard-to-reproduce issues.

https://github.com/DetachHead/basedpyright/blob/6c2a19929d539a7d5c5e9675a2bc07ef34fa0422/packages/pyright-internal/src/analyzer/program.ts#L2023-L2082

**Comment by DetachHead** [comment]
yeah i've seen that failure before, no idea what causes it but re-running the job usually fixes it. i'll open a separate issue to investigate

**Review by DetachHead — APPROVED** [review]
