### PR TITLE
change the format of the diagnostic counts to avoid pluralizing because "informations" looks weird

### LINKED ISSUE #58: rename "informations"
currently it says:
```
0 errors, 0 warnings, 0 informations
```

maybe it should be something like:
```
error: 0, warning: 0, information: 0
```

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #58

### CODE REVIEW

File: packages/pyright-internal/src/pyright.ts [hunk 1]
```diff
@@ -928,9 +928,7 @@ function reportDiagnosticsAsText(
     });
 
     console.info(
-        `${errorCount.toString()} ${errorCount === 1 ? 'error' : 'errors'}, ` +
-            `${warningCount.toString()} ${warningCount === 1 ? 'warning' : 'warnings'}, ` +
-            `${informationCount.toString()} ${informationCount === 1 ? 'information' : 'informations'} `
+        `error: ${errorCount.toString()}, warning: ${warningCount.toString()}, information: ${informationCount.toString()}`
```
Comment (DetachHead) [inline packages/pyright-internal/src/pyright.ts:931]: instead rename informations to notes
