### PR TITLE
remove support for relative imports that are not prefixed with a `.`

### LINKED ISSUE #76: pyright incorrectly adds the script directory to the module search path
```py
# foo/a.py
a = 1
```
```py
# foo/b.py
import a # no pyright error
```
```py
# main.py
import foo.b
```

running `python main.py` will cause the following error:
```
> python main.py
Traceback (most recent call last):
  File "C:\project\main.py", line 4, in <module>
    import foo.b
  File "C:\project\foo\b.py", line 4, in <module>
    import a  # no error
    ^^^^^^^^
ModuleNotFoundError: No module named 'a'
```

rejected upstream issue: https://github.com/microsoft/pyright/issues/7226

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #76

### CODE REVIEW

File: packages/pyright-internal/src/tests/fourslash/completions.parentFolder.fourslash.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@
 //// #empty
 
 // @ts-ignore
-await helper.verifyCompletion('included', 'markdown', {
+await helper.verifyCompletion('excluded', 'markdown', {
     marker: {
         completions: [{ label: 'data_processing', kind: Consts.CompletionItemKind.Module }],
```
Comment (DetachHead) [inline packages/pyright-internal/src/tests/fourslash/completions.parentFolder.fourslash.ts:15]: should it be `python.data_processing` instead?

Comment (DetachHead) [reply packages/pyright-internal/src/tests/fourslash/completions.parentFolder.fourslash.ts:15]: nah
