### PR TITLE
fix: error message for pyright executable fallback

### LINKED ISSUE #197: "failed to find pyright executable, falling back to bundled: " message is wrong
from `extension.activate`

### PR DESCRIPTION
**Pull request by veeceey**
## Summary

Improves the warning message when the pyright executable is not found and the extension falls back to the bundled version. The message now shows both the path where the executable was expected and the path to the bundled version.

## Changes

**Before:**
```
failed to find pyright executable, falling back to bundled: /path/to/expected/executable
```

**After:**
```
failed to find pyright executable at /path/to/expected/executable, falling back to bundled at /path/to/bundled/server.js
```

## Related Issues

Fixes #197

## Test Plan

This change improves an error message only. Manual verification would require:
1. Setting `basedpyright.importStrategy` to `"fromEnvironment"`
2. Not having basedpyright installed in the active Python environment
3. Observing the console output

### CODE REVIEW

File: packages/vscode-pyright/src/extension.ts [hunk 1]
```diff
@@ -144,7 +144,8 @@ export async function activate(context: ExtensionContext) {
                     : [copiedExecutablePath, cliArgs];
             serverOptions = { command, transport: TransportKind.stdio, args };
         } else {
-            console.warn('failed to find pyright executable, falling back to bundled:', executablePath);
+            const bundledPath = context.asAbsolutePath(path.join('dist', 'server.js'));
```
Comment (DetachHead) [inline packages/vscode-pyright/src/extension.ts]: this is duplicated from the `bundlePath` variable below. we should move it outside of the `if` statement so it can be used in both places

Comment (veeceey) [reply packages/vscode-pyright/src/extension.ts]: Done\! I've hoisted the `bundlePath` declaration outside the `if` block so it can be used in both the warning message and the bundled server options, avoiding the duplication.
