### PR TITLE
fix `reportIncompatibleUnannotatedOverride` false positive & fix case where it changes the behavior of `reportIncompatibleMethodOverride`

### LINKED ISSUE #1247: `reportIncompatibleUnannotatedOverride` false positive when overridden type has an incompatible inferred type
### Description

Code sample in [basedpyright playground](https://basedpyright.com/?pythonVersion=3.13&typeCheckingMode=all&reportUnannotatedClassAttribute=false&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2AsAFB10DGl5Azq1AGJhgBcdUQVHK9CxMlQDaARgA0UAEwBdKAF4o0hrWZsOAIXIgAFNzABKfrSFQAJiWBQA%2Bo9TFnR1iUrALA60M9vADpyNUUoAGIoMnAQUQB5ADcYpDtYRBIoACJUGCzMDhQwfBgAC0zWcghMtigAIzZM%2BARMrKJSCkoZeWUsrToQEmSqR2aSIwNjMxCzSLEOqTlFJSA)

```python
from typing import Literal


class Foo:
    a: Literal[1, 2] = 1

class Bar(Foo):
    def __init__(self):
        self.a = 2 # error: Override type "int" is not the same as base type "Literal[1, 2]"

# this is safe because the type doesn't actually get widened to int
reveal_type(Bar().a) # Literal[1, 2]
```

### LINKED ISSUE #1288: enabling `reportIncompatibleUnannotatedOverride` causes `reportIncompatibleMethodOverride` when a subtype of a subtype overrides a property with an attribute
### Description

Code sample in [basedpyright playground](https://basedpyright.com/?typeCheckingMode=all&code=GYJw9gtgBAhgRgYygSwgBzCALlAggIQGEAaWOAZyxBgSwgFMsALMAEwFgAoLhAGxnLkoAMTBgAFAUIBKAFxcoiqAAE04NPWwBPBUuXxK1Wg2Ztdi1vWBRgY8eXq9g0qAFoAfCgB2WWVAB0gVzBnHwCQvgwIOKiYHLmNmJQALxQAIwhYYJQkQBe4pEg8ZxKiWApUABMUADEUCD0GNgAkl4IkGgwWMhwvPQAsowsrADyAG6aIMiWpGBevFpQAO5M9F71jZhYre3oXT19AKpeMF5eYFhd9KMTIFOWKEJr8H2sQA)

```python
from abc import ABC, abstractmethod

class Foo(ABC):
    @property
    @abstractmethod
    def foo(self) -> int: ...


class Bar(Foo):
    foo = 1

class Baz(Bar):
    foo = 2 # reportIncompatibleMethodOverride, only when reportIncompatibleUnannotatedOverride is enabled
```

this should probably report `reportIncompatibleUnannotatedOverride` instead

### PR DESCRIPTION
**Pull request by DetachHead**
- fixes #1247
- fixes #1288

### CODE REVIEW

File: packages/pyright-internal/src/common/configOptions.ts [hunk 1]
```diff
@@ -1048,7 +1048,7 @@ export const getRecommendedDiagnosticRuleSet = (): DiagnosticRuleSet => ({
     reportUnusedParameter: 'warning',
     reportImplicitAbstractClass: 'warning',
     reportUnannotatedClassAttribute: 'warning',
-    reportIncompatibleUnannotatedOverride: 'none', // TODO: change to error when we're confident there's no performance issues with this rule
+    reportIncompatibleUnannotatedOverride: 'error', // TODO: change to error when we're confident there's no performance issues with this rule
```
Comment (DetachHead) [inline packages/pyright-internal/src/common/configOptions.ts:1051]: revert this

**Comment by DetachHead** [comment]
looks like the `reportIncompatibleMethodOverride` errors from the primer are an existing issue. see #1288
