### PR TITLE
fix $schema being reported as unrecognized setting in config files

### LINKED ISSUE #1651: Config contains unrecognized setting "$schema"
### Description

`pyrightconfig.json` supports JSON schema for ease of editing:

```jsonc
{
    "$schema": "https://raw.githubusercontent.com/microsoft/pyright/main/packages/vscode-pyright/schemas/pyrightconfig.schema.json",

    "typeCheckingMode": "basic",
}
```

but VSCode basedpyright pops up an error when using that:

Image

(the checker still works, so just a superfluous error)

### PR DESCRIPTION
**Pull request by jaenw**
## Summary
- Added `$schema` to the list of recognized config options
- Prevents spurious error when using JSON schema validation in config files
- Fixes #1651

### CODE REVIEW

File: packages/pyright-internal/src/common/configOptions.ts [hunk 1]
```diff
@@ -1582,6 +1582,7 @@ export class ConfigOptions {
         const unusedConfigDetector = new UnusedConfigDetector<Record<string, object>>(configObj, [
             'extends',
             'executionEnvironments',
+            '$schema',
```
Comment (DetachHead) [inline packages/pyright-internal/src/common/configOptions.ts]: we should split that comment up so that each one has a clear explanation next to it

```suggestion
const unusedConfigDetector = new UnusedConfigDetector<Record<string, object>>(configObj, [
            // we initialize with these because they option get read elsewhere:
            'extends',
            'executionEnvironments',
            // vscode supports setting a "$schema" attribute in a json file to specify the schema to validate it against. see https://code.visualstudio.com/docs/languages/json#_mapping-in-the-json
            '$schema',
```

File: packages/pyright-internal/src/tests/config.test.ts [hunk 2]
```diff
@@ -219,6 +219,25 @@ describe(`config test'}`, () => {
...
+            };
+
+            const fs = new TestFileSystem(/* ignoreCase */ false);
+            const console = new ErrorTrackingNullConsole();
+
+            const sp = createServiceProvider(fs, console);
+            configOptions.initializeFromJson(json, cwd, sp, new NoAccessHost());
+
+            assert.deepStrictEqual(console.errors, []);
+        });
```
Comment (DetachHead) [inline packages/pyright-internal/src/tests/config.test.ts]: this shouldn't be inside the "invalid config" section if we aren't expecting any errors
```suggestion
    test('$schema is recognized', () => {
        const cwd = UriEx.file(normalizePath(process.cwd()));

        const configOptions = new ConfigOptions(cwd);

        const json = {
            $schema:
                'https://raw.githubusercontent.com/microsoft/pyright/main/packages/vscode-pyright/schemas/pyrightconfig.schema.json',
            typeCheckingMode: 'basic',
        };

        const fs = new TestFileSystem(/* ignoreCase */ false);
        const console = new ErrorTrackingNullConsole();

        const sp = createServiceProvider(fs, console);
        configOptions.initializeFromJson(json, cwd, sp, new NoAccessHost());

        assert.deepStrictEqual(console.errors, []);
    });
describe('invalid config', () => {
```
