### PR TITLE
fix suggested import code action not working when the whole module is already imported

### LINKED ISSUE #106: import suggestion code actions don't work if the whole module is already imported
```py
import inspect

stack()
```
`ctrl+.` on `stack` will show the suggested import, but it does nothing. it needs to modify the usage to `inspect.stack` like the autocomplete suggestion does

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #106

### CODE REVIEW

File: packages/pyright-internal/src/tests/fourslash/importSuggestionWholeModuleImported.invokeCodeAction.fourslash.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+                },
+                kind: 'quickfix',
+            },
+        ],
+    };
+
+    //@ts-expect-error https://github.com/DetachHead/basedpyright/issues/86
+    await helper.verifyCodeActions('included', {
+        noImportMarker: { codeActions: [] },
+        startMarker: codeActions,
```
Comment (KotlinIsland) [inline packages/pyright-internal/src/tests/fourslash/importSuggestionWholeModuleImported.invokeCodeAction.fourslash.ts:29]: PEBKAC error

**Review by KotlinIsland — APPROVED** [review]

File: packages/pyright-internal/src/tests/fourslash/importSuggestionWholeModuleImported.invokeCodeAction.fourslash.ts (hunk 1 above)
Comment (DetachHead) [reply packages/pyright-internal/src/tests/fourslash/importSuggestionWholeModuleImported.invokeCodeAction.fourslash.ts:29]: really dumb that this fourslash thing doesn't complain on invalid markers here
